services:
  guitar-shop.server.mongo:
    image: mongo:7.0.9
    restart: always
    container_name: guitar-shop-server_mongoDb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - guitar_shop_server_data:/data/db

volumes:
  guitar_shop_server_data:
