@host = http://localhost:3000
@productId = 6655faf5d8cafe6e5da828fd

### Create a new product
POST {{host}}/api/products HTTP/1.1
Content-Type: application/json

{
  "title": "Fender Stratocaster",
  "description": "A classic guitar model known for its versatility and tone.",
  "photoId": "1234",
  "guitarType": "акустика",
  "article": "The article of the product",
  "guitarStringType": 7,
  "price": 25000
}


### Get product by ID
GET {{host}}/api/products/{{productId}} HTTP/1.1


### Update product
PATCH {{host}}/api/products/{{productId}} HTTP/1.1
Content-Type: application/json

{
  "title": "AAA Fender Stratocaster"
}


### Delete product by ID
DELETE {{host}}/api/products/{{productId}} HTTP/1.1