@host = http://localhost:3000
@userId = 665370cf3c05a9828e60a286
@accessToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjU0ZTRkZTFjMjJiMGZjZjYwYjU3YTEiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwibmFtZSI6Iktla3NBIiwiaWF0IjoxNzE2OTM1NTA5LCJleHAiOjE3MTY5Mzg1MDl9.0DszBkcahlaSbYrA6B9CXyCW48_TPMm1GqWtT2VvB4brzOG7TR0okYzHrQd-e9_2gPSdPzi-QmcwjkWatbHDjQ

### Create a new user
POST {{host}}/api/users HTTP/1.1
Content-Type: application/json

{
  "email": "user3@notfound.local",
  "name": "KeksA",
  "password": "123456"
}


### Get user by ID
GET {{host}}/api/users/{{userId}} HTTP/1.1


### Update user
PATCH {{host}}/api/users/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "name": "AAA2"
}


### Delete user by ID
DELETE {{host}}/api/users/{{userId}} HTTP/1.1


### Login user by email and password
POST {{host}}/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user2@notfound.local",
  "password": "123456"
}

### Check JWT token
POST {{host}}/api/users/check HTTP/1.1
Authorization: Bearer {{accessToken}}
